<!-- Copyright © Erickson Lopez. MIT License. -->
<Project>
  <PropertyGroup Condition="'$(IsAotCompatible)' == 'false' or '$(IsTestOrSampleProject)' == 'true'">
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <EnableAotAnalyzer>false</EnableAotAnalyzer>
    <EnableSingleFileAnalyzer>false</EnableSingleFileAnalyzer>
    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
    <SuppressAotAnalysisWarnings>true</SuppressAotAnalysisWarnings>
  </PropertyGroup>

  <ItemGroup Condition="$(MSBuildProjectDirectory.Contains('tests'))">
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
