// Copyright © Erickson Lopez. MIT License.

using System;

namespace EricksonLopez.Security.WebAuthn.Fido2.Models;

/// <summary>
/// Represents the Attested Credential Data structure parsed from an authenticator registration response.
/// </summary>
public sealed record AttestedCredentialData
{
    /// <summary>
    /// Gets the Authenticator Attestation GUID (AAGUID, 16 bytes).
    /// </summary>
    public Guid Aaguid { get; init; }

    /// <summary>
    /// Gets the unique Credential ID generated by the authenticator.
    /// </summary>
    public byte[] CredentialId { get; init; }

    /// <summary>
    /// Gets the parsed COSE public key.
    /// </summary>
    public CosePublicKey PublicKey { get; init; }

    /// <summary>
    /// Gets the raw bytes of the attested credential data.
    /// </summary>
    public byte[] RawBytes { get; init; }

    /// <summary>
    /// Initializes a new instance of the <see cref="AttestedCredentialData"/> record with the specified AAGUID, credential ID, public key, and raw bytes.
    /// </summary>
    /// <param name="aaguid">The Authenticator Attestation GUID (AAGUID).</param>
    /// <param name="credentialId">The unique Credential ID generated by the authenticator.</param>
    /// <param name="publicKey">The parsed COSE public key.</param>
    /// <param name="rawBytes">The raw bytes of the attested credential data.</param>
    /// <exception cref="ArgumentNullException"><paramref name="credentialId"/>, <paramref name="publicKey"/>, or <paramref name="rawBytes"/> is <see langword="null"/></exception>
    public AttestedCredentialData(Guid aaguid, byte[] credentialId, CosePublicKey publicKey, byte[] rawBytes)
    {
        Aaguid = aaguid;
        CredentialId = credentialId ?? throw new ArgumentNullException(nameof(credentialId));
        PublicKey = publicKey ?? throw new ArgumentNullException(nameof(publicKey));
        RawBytes = rawBytes ?? throw new ArgumentNullException(nameof(rawBytes));
    }
}
