// Copyright © Erickson Lopez. MIT License.

using System;
using System.Collections.Generic;
using EricksonLopez.Security.WebAuthn.Fido2.Enums;

namespace EricksonLopez.Security.WebAuthn.Fido2.Models;

/// <summary>
/// Represents all configuration parameters required by <c>navigator.credentials.get()</c> to authenticate with an existing WebAuthn credential.
/// </summary>
public sealed record CredentialRequestOptions
{
    /// <summary>
    /// Gets the cryptographically random challenge byte array generated by the server.
    /// </summary>
    public byte[] Challenge { get; init; }

    /// <summary>
    /// Gets the Relying Party identifier (domain name, e.g. "example.com").
    /// </summary>
    public string RpId { get; init; }

    /// <summary>
    /// Gets the timeout in milliseconds for the ceremony.
    /// </summary>
    public ulong TimeoutMilliseconds { get; init; } = 60000;

    /// <summary>
    /// Gets the optional list of allowed credentials (omitted in discoverable credential / passkey autofill ceremonies).
    /// </summary>
    public IReadOnlyList<PublicKeyCredentialDescriptor>? AllowCredentials { get; init; }

    /// <summary>
    /// Gets the user verification requirement (e.g. Preferred or Required).
    /// </summary>
    public UserVerificationRequirement UserVerification { get; init; } = UserVerificationRequirement.Preferred;

    /// <summary>
    /// Initializes a new instance of the <see cref="CredentialRequestOptions"/> record with the specified challenge and Relying Party identifier.
    /// </summary>
    /// <param name="challenge">The cryptographically random challenge byte array generated by the server.</param>
    /// <param name="rpId">The Relying Party identifier (domain name).</param>
    /// <exception cref="ArgumentNullException"><paramref name="challenge"/> is <see langword="null"/></exception>
    /// <exception cref="ArgumentException"><paramref name="rpId"/> is <see langword="null"/>, empty, or whitespace</exception>
    public CredentialRequestOptions(byte[] challenge, string rpId)
    {
        ArgumentNullException.ThrowIfNull(challenge);
        ArgumentException.ThrowIfNullOrWhiteSpace(rpId);

        Challenge = challenge;
        RpId = rpId;
    }
}
