// Copyright © Erickson Lopez. MIT License.

using System;
using System.Collections.Generic;
using EricksonLopez.Security.WebAuthn.Fido2.Enums;

namespace EricksonLopez.Security.WebAuthn.Fido2.Models;

/// <summary>
/// Represents all configuration parameters required by <c>navigator.credentials.create()</c> to generate a new WebAuthn credential.
/// </summary>
public sealed record CredentialCreateOptions
{
    /// <summary>
    /// Gets the Relying Party information.
    /// </summary>
    public RelyingPartyIdentity Rp { get; init; }

    /// <summary>
    /// Gets the user entity information.
    /// </summary>
    public PublicKeyCredentialUserEntity User { get; init; }

    /// <summary>
    /// Gets the cryptographically random challenge byte array generated by the server.
    /// </summary>
    public byte[] Challenge { get; init; }

    /// <summary>
    /// Gets the list of supported cryptographic parameters.
    /// </summary>
    public IReadOnlyList<PublicKeyCredentialParameters> PubKeyCredParams { get; init; }

    /// <summary>
    /// Gets the timeout in milliseconds for the ceremony.
    /// </summary>
    public ulong TimeoutMilliseconds { get; init; } = 60000;

    /// <summary>
    /// Gets the optional list of credentials already registered for this user (to prevent re-registering the same authenticator).
    /// </summary>
    public IReadOnlyList<PublicKeyCredentialDescriptor>? ExcludeCredentials { get; init; }

    /// <summary>
    /// Gets the authenticator attachment modality preference (e.g. Platform vs CrossPlatform).
    /// </summary>
    public AuthenticatorAttachment? AuthenticatorAttachment { get; init; }

    /// <summary>
    /// Gets the resident key / discoverable credential requirement (Passkey mode).
    /// </summary>
    public ResidentKeyRequirement ResidentKey { get; init; } = ResidentKeyRequirement.Preferred;

    /// <summary>
    /// Gets the user verification requirement (e.g. Preferred or Required).
    /// </summary>
    public UserVerificationRequirement UserVerification { get; init; } = UserVerificationRequirement.Preferred;

    /// <summary>
    /// Gets the attestation conveyance preference (default is None for privacy).
    /// </summary>
    public AttestationConveyancePreference Attestation { get; init; } = AttestationConveyancePreference.None;

    /// <summary>
    /// Initializes a new instance of the <see cref="CredentialCreateOptions"/> record with the required Relying Party, user, challenge, and cryptographic parameters.
    /// </summary>
    /// <param name="rp">The Relying Party identity information.</param>
    /// <param name="user">The user entity account information.</param>
    /// <param name="challenge">The cryptographically random challenge byte array generated by the server.</param>
    /// <param name="pubKeyCredParams">The list of supported cryptographic parameters.</param>
    /// <exception cref="ArgumentNullException"><paramref name="rp"/>, <paramref name="user"/>, <paramref name="challenge"/>, or <paramref name="pubKeyCredParams"/> is <see langword="null"/></exception>
    public CredentialCreateOptions(
        RelyingPartyIdentity rp,
        PublicKeyCredentialUserEntity user,
        byte[] challenge,
        IReadOnlyList<PublicKeyCredentialParameters> pubKeyCredParams)
    {
        ArgumentNullException.ThrowIfNull(rp);
        ArgumentNullException.ThrowIfNull(user);
        ArgumentNullException.ThrowIfNull(challenge);
        ArgumentNullException.ThrowIfNull(pubKeyCredParams);

        Rp = rp;
        User = user;
        Challenge = challenge;
        PubKeyCredParams = pubKeyCredParams;
    }
}
