// Copyright © Erickson Lopez. MIT License.

using System;
using System.Collections.Generic;
using EricksonLopez.Security.WebAuthn.Fido2.Enums;

namespace EricksonLopez.Security.WebAuthn.Fido2.Models;

/// <summary>
/// Represents the attributes necessary to identify a public key credential.
/// </summary>
public sealed record PublicKeyCredentialDescriptor
{
    /// <summary>
    /// Gets the credential type.
    /// </summary>
    public PublicKeyCredentialType Type { get; init; } = PublicKeyCredentialType.PublicKey;

    /// <summary>
    /// Gets the credential ID (binary identifier generated by the authenticator).
    /// </summary>
    public byte[] Id { get; init; }

    /// <summary>
    /// Gets the optional list of transport hints for reaching the authenticator.
    /// </summary>
    public IReadOnlyList<string>? Transports { get; init; }

    /// <summary>
    /// Initializes a new instance of the <see cref="PublicKeyCredentialDescriptor"/> record.
    /// </summary>
    /// <param name="id">The credential ID byte array.</param>
    /// <param name="transports">Optional transport hints (e.g. "usb", "nfc", "ble", "internal").</param>
    /// <exception cref="ArgumentNullException"><paramref name="id"/> is <see langword="null"/></exception>
    public PublicKeyCredentialDescriptor(byte[] id, IReadOnlyList<string>? transports = null)
    {
        ArgumentNullException.ThrowIfNull(id);
        Id = id;
        Transports = transports;
    }
}
