<!-- Copyright © Erickson Lopez. MIT License. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Unit tests for EricksonLopez.Security.ZeroTrust ABAC policy engine.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Security.ZeroTrust\EricksonLopez.Security.ZeroTrust.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AwesomeAssertions" />
  </ItemGroup>

</Project>
