// Copyright © Erickson Lopez. MIT License.

namespace EricksonLopez.Security.Saml2.Models;

using System;
using EricksonLopez.Security.Saml2.Enums;

/// <summary>
/// Represents a SAML 2.0 AuthnRequest message generated by the Service Provider to initiate SSO.
/// </summary>
public sealed record Saml2AuthnRequest
{
    /// <summary>
    /// Gets the unique message identifier (e.g. "_guid").
    /// </summary>
    public string Id { get; init; }

    /// <summary>
    /// Gets the Entity ID of the Service Provider issuer.
    /// </summary>
    public string Issuer { get; init; }

    /// <summary>
    /// Gets the issue timestamp.
    /// </summary>
    public DateTimeOffset IssueInstant { get; init; }

    /// <summary>
    /// Gets the destination SSO endpoint URI at the Identity Provider.
    /// </summary>
    public string Destination { get; init; }

    /// <summary>
    /// Gets the Assertion Consumer Service (ACS) endpoint URL where response will be sent.
    /// </summary>
    public string AssertionConsumerServiceUrl { get; init; }

    /// <summary>
    /// Gets the protocol binding for receiving the response.
    /// </summary>
    public Saml2Binding ProtocolBinding { get; init; }

    /// <summary>
    /// Gets the requested NameID format policy.
    /// </summary>
    public Saml2NameIdFormat NameIdFormat { get; init; }

    /// <summary>
    /// Gets a value indicating whether the IdP must re-authenticate the user forcibly.
    /// </summary>
    public bool ForceAuthn { get; init; }

    /// <summary>
    /// Gets a value indicating whether authentication must proceed without user interaction (passive).
    /// </summary>
    public bool IsPassive { get; init; }

    /// <summary>
    /// Gets the optional RelayState state string.
    /// </summary>
    public string? RelayState { get; init; }

    /// <summary>
    /// Gets the raw XML string of the request.
    /// </summary>
    public string RawXml { get; init; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Saml2AuthnRequest"/> record with the specified parameters.
    /// </summary>
    /// <param name="id">The unique request message identifier.</param>
    /// <param name="issuer">The Entity ID of the Service Provider issuer.</param>
    /// <param name="issueInstant">The timestamp when the request was generated.</param>
    /// <param name="destination">The destination SSO endpoint URI at the Identity Provider.</param>
    /// <param name="assertionConsumerServiceUrl">The Assertion Consumer Service (ACS) endpoint URL where the response will be sent.</param>
    /// <param name="rawXml">The raw XML string representation of the request.</param>
    /// <param name="protocolBinding">The protocol binding for receiving the response.</param>
    /// <param name="nameIdFormat">The requested NameID format policy.</param>
    /// <param name="forceAuthn">A value indicating whether the IdP must forcibly re-authenticate the user.</param>
    /// <param name="isPassive">A value indicating whether authentication must proceed without user interaction.</param>
    /// <param name="relayState">The optional state string preserved across SSO redirects.</param>
    /// <exception cref="ArgumentException"><paramref name="id"/>, <paramref name="issuer"/>, <paramref name="destination"/>, <paramref name="assertionConsumerServiceUrl"/>, or <paramref name="rawXml"/> is <see langword="null"/>, empty, or whitespace</exception>
    public Saml2AuthnRequest(
        string id,
        string issuer,
        DateTimeOffset issueInstant,
        string destination,
        string assertionConsumerServiceUrl,
        string rawXml,
        Saml2Binding protocolBinding = Saml2Binding.HttpPost,
        Saml2NameIdFormat nameIdFormat = Saml2NameIdFormat.Unspecified,
        bool forceAuthn = false,
        bool isPassive = false,
        string? relayState = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(id);
        ArgumentException.ThrowIfNullOrWhiteSpace(issuer);
        ArgumentException.ThrowIfNullOrWhiteSpace(destination);
        ArgumentException.ThrowIfNullOrWhiteSpace(assertionConsumerServiceUrl);
        ArgumentException.ThrowIfNullOrWhiteSpace(rawXml);

        Id = id;
        Issuer = issuer;
        IssueInstant = issueInstant;
        Destination = destination;
        AssertionConsumerServiceUrl = assertionConsumerServiceUrl;
        RawXml = rawXml;
        ProtocolBinding = protocolBinding;
        NameIdFormat = nameIdFormat;
        ForceAuthn = forceAuthn;
        IsPassive = isPassive;
        RelayState = relayState;
    }
}
