// Copyright © Erickson Lopez. MIT License.

namespace EricksonLopez.Security.Saml2.Models;

using System;

/// <summary>
/// Represents a SAML 2.0 Single Logout Request message generated by the Service Provider
/// to initiate federated session termination with the Identity Provider.
/// </summary>
public sealed record Saml2LogoutRequest
{
    /// <summary>Gets the unique message identifier (e.g. "_guid").</summary>
    public string Id { get; init; }

    /// <summary>Gets the Entity ID of the SP issuer.</summary>
    public string Issuer { get; init; }

    /// <summary>Gets the issue timestamp.</summary>
    public DateTimeOffset IssueInstant { get; init; }

    /// <summary>Gets the destination Single Logout Service (SLS) endpoint at the IdP.</summary>
    public string Destination { get; init; }

    /// <summary>
    /// Gets the NameID of the principal whose session is being terminated.
    /// Must match the NameID received in the original assertion.
    /// </summary>
    public Saml2NameId NameId { get; init; }

    /// <summary>
    /// Gets the optional session index from the original assertion's AuthnStatement.
    /// Allows the IdP to terminate the specific session rather than all sessions.
    /// </summary>
    public string? SessionIndex { get; init; }

    /// <summary>Gets the raw XML string of the logout request.</summary>
    public string RawXml { get; init; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Saml2LogoutRequest"/> record with the specified session termination data.
    /// </summary>
    /// <param name="id">The unique message identifier.</param>
    /// <param name="issuer">The Entity ID of the Service Provider issuer.</param>
    /// <param name="issueInstant">The timestamp when the request was generated.</param>
    /// <param name="destination">The destination Single Logout Service (SLS) endpoint at the Identity Provider.</param>
    /// <param name="nameId">The NameID of the principal whose session is being terminated.</param>
    /// <param name="rawXml">The raw XML string representation of the logout request.</param>
    /// <param name="sessionIndex">The optional session index from the original assertion.</param>
    /// <exception cref="ArgumentNullException"><paramref name="nameId"/> is <see langword="null"/></exception>
    /// <exception cref="ArgumentException"><paramref name="id"/>, <paramref name="issuer"/>, <paramref name="destination"/>, or <paramref name="rawXml"/> is <see langword="null"/>, empty, or whitespace</exception>
    public Saml2LogoutRequest(
        string id,
        string issuer,
        DateTimeOffset issueInstant,
        string destination,
        Saml2NameId nameId,
        string rawXml,
        string? sessionIndex = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(id);
        ArgumentException.ThrowIfNullOrWhiteSpace(issuer);
        ArgumentException.ThrowIfNullOrWhiteSpace(destination);
        ArgumentException.ThrowIfNullOrWhiteSpace(rawXml);
        ArgumentNullException.ThrowIfNull(nameId);

        Id = id;
        Issuer = issuer;
        IssueInstant = issueInstant;
        Destination = destination;
        NameId = nameId;
        SessionIndex = sessionIndex;
        RawXml = rawXml;
    }
}
